/*

Work in progress

*/

CREATE TEMP FUNCTION udf_js_histogram_row(
  histograms STRUCT<
--  all STRUCT<
--    uptake_remote_content_result_1 ARRAY<STRUCT<key STRING, value STRING>>
--  >,
    content STRUCT<
      cert_validation_success_by_ca STRING,
      checkerboard_severity STRING,
      composite_time STRING,
      content_paint_time STRING,
      cycle_collector_max_pause STRING,
      devtools_aboutdebugging_opened_count STRING,
      devtools_accessibility_picker_time_active_seconds STRING,
      devtools_accessibility_service_time_active_seconds STRING,
      devtools_accessibility_time_active_seconds STRING,
      devtools_animationinspector_opened_count STRING,
      devtools_browserconsole_opened_count STRING,
      devtools_canvasdebugger_opened_count STRING,
      devtools_computedview_opened_count STRING,
      devtools_custom_opened_count STRING,
      devtools_dom_opened_count STRING,
      devtools_eyedropper_opened_count STRING,
      devtools_fontinspector_opened_count STRING,
      devtools_inspector_opened_count STRING,
      devtools_jsbrowserdebugger_opened_count STRING,
      devtools_jsdebugger_opened_count STRING,
      devtools_jsprofiler_opened_count STRING,
      devtools_layoutview_opened_count STRING,
      devtools_memory_opened_count STRING,
      devtools_menu_eyedropper_opened_count STRING,
      devtools_netmonitor_opened_count STRING,
      devtools_options_opened_count STRING,
      devtools_paintflashing_opened_count STRING,
      devtools_picker_eyedropper_opened_count STRING,
      devtools_responsive_opened_count STRING,
      devtools_ruleview_opened_count STRING,
      devtools_scratchpad_opened_count STRING,
      devtools_scratchpad_window_opened_count STRING,
      devtools_shadereditor_opened_count STRING,
      devtools_storage_opened_count STRING,
      devtools_styleeditor_opened_count STRING,
      devtools_toolbox_time_active_seconds STRING,
      devtools_webaudioeditor_opened_count STRING,
      devtools_webconsole_opened_count STRING,
      devtools_webide_opened_count STRING,
      fx_page_load_ms_2 STRING,
      fx_searchbar_selected_result_method STRING,
      fx_urlbar_selected_result_index STRING,
      fx_urlbar_selected_result_index_by_type ARRAY<STRUCT<key STRING, value STRING>>,
      fx_urlbar_selected_result_method STRING,
      fx_urlbar_selected_result_type STRING,
      gc_animation_ms STRING,
      gc_max_pause_ms_2 STRING,
      geolocation_request_granted STRING,
      ghost_windows STRING,
      gpu_process_initialization_time_ms STRING,
      gpu_process_launch_time_ms_2 STRING,
      http_channel_disposition STRING,
      http_pageload_is_ssl STRING,
      http_transaction_is_ssl STRING,
      input_event_response_coalesced_ms STRING,
      ipc_read_main_thread_latency_ms ARRAY<STRUCT<key STRING, value STRING>>,
      memory_heap_allocated STRING,
      memory_resident_fast STRING,
      memory_unique STRING,
      memory_unique_content_startup STRING,
      memory_vsize STRING,
      memory_vsize_max_contiguous STRING,
      network_cache_metadata_first_read_time_ms STRING,
      network_cache_v2_hit_time_ms STRING,
      network_cache_v2_miss_time_ms STRING,
      number_of_profiles STRING,
      plugin_shutdown_ms STRING,
      pwmgr_form_autofill_result STRING,
      pwmgr_login_page_safety STRING,
      pwmgr_manage_copied_password STRING,
      pwmgr_manage_copied_username STRING,
      pwmgr_manage_deleted STRING,
      pwmgr_manage_opened STRING,
      sandbox_rejected_syscalls ARRAY<STRUCT<key STRING, value STRING>>,
      ssl_handshake_result STRING,
      ssl_handshake_version STRING,
      ssl_tls12_intolerance_reason_pre STRING,
      ssl_tls13_intolerance_reason_pre STRING,
      time_to_dom_complete_ms STRING,
      time_to_dom_content_loaded_end_ms STRING,
      time_to_dom_content_loaded_start_ms STRING,
      time_to_dom_interactive_ms STRING,
      time_to_dom_loading_ms STRING,
      time_to_first_click_ms STRING,
      time_to_first_interaction_ms STRING,
      time_to_first_key_input_ms STRING,
      time_to_first_mouse_move_ms STRING,
      time_to_first_scroll_ms STRING,
      time_to_load_event_end_ms STRING,
      time_to_load_event_start_ms STRING,
      time_to_non_blank_paint_ms STRING,
      time_to_response_start_ms STRING,
      webext_content_script_injection_ms STRING,
      webext_storage_local_get_ms STRING,
      webext_storage_local_set_ms STRING,
      webvr_time_spent_viewing_in_2d STRING,
      webvr_users_view_in STRING
    >,
    gpu STRUCT<
      checkerboard_severity STRING,
      composite_time STRING,
      content_frame_time STRING,
      gpu_process_initialization_time_ms STRING,
      webvr_time_spent_viewing_in_oculus STRING,
      webvr_time_spent_viewing_in_openvr STRING,
      webvr_users_view_in STRING,
      ipc_read_main_thread_latency_ms ARRAY<STRUCT<key STRING, value STRING>>
    >,
    parent STRUCT<
      a11y_consumers STRING,
      a11y_instantiated_flag STRING,
      cert_validation_success_by_ca STRING,
      checkerboard_severity STRING,
      composite_time STRING,
      content_paint_time STRING,
      cookie_behavior STRING,
      cycle_collector_max_pause STRING,
      devtools_about_devtools_opened_key STRING,
      devtools_about_devtools_opened_reason STRING,
      devtools_aboutdebugging_opened_count STRING,
      devtools_accessibility_picker_time_active_seconds STRING,
      devtools_accessibility_service_time_active_seconds STRING,
      devtools_accessibility_time_active_seconds STRING,
      devtools_animationinspector_opened_count STRING,
      devtools_browserconsole_opened_count STRING,
      devtools_canvasdebugger_opened_count STRING,
      devtools_computedview_opened_count STRING,
      devtools_custom_opened_count STRING,
      devtools_dom_opened_count STRING,
      devtools_entry_point STRING,
      devtools_eyedropper_opened_count STRING,
      devtools_fonteditor_font_type_displayed STRING,
      devtools_fonteditor_n_font_axes STRING,
      devtools_fonteditor_n_fonts_rendered STRING,
      devtools_fontinspector_opened_count STRING,
      devtools_inspector_opened_count STRING,
      devtools_jsbrowserdebugger_opened_count STRING,
      devtools_jsdebugger_opened_count STRING,
      devtools_jsprofiler_opened_count STRING,
      devtools_layoutview_opened_count STRING,
      devtools_memory_opened_count STRING,
      devtools_menu_eyedropper_opened_count STRING,
      devtools_netmonitor_opened_count STRING,
      devtools_options_opened_count STRING,
      devtools_paintflashing_opened_count STRING,
      devtools_picker_eyedropper_opened_count STRING,
      devtools_responsive_opened_count STRING,
      devtools_ruleview_opened_count STRING,
      devtools_scratchpad_opened_count STRING,
      devtools_scratchpad_window_opened_count STRING,
      devtools_shadereditor_opened_count STRING,
      devtools_storage_opened_count STRING,
      devtools_styleeditor_opened_count STRING,
      devtools_toolbox_time_active_seconds STRING,
      devtools_webaudioeditor_opened_count STRING,
      devtools_webconsole_opened_count STRING,
      devtools_webide_opened_count STRING,
      dns_failed_lookup_time STRING,
      dns_lookup_time STRING,
      fx_new_window_ms STRING,
      fx_page_load_ms_2 STRING,
      fx_searchbar_selected_result_method STRING,
      fx_session_restore_restore_window_ms STRING,
      fx_session_restore_startup_init_session_ms STRING,
      fx_session_restore_startup_onload_initial_window_ms STRING,
      fx_tab_close_time_anim_ms STRING,
      fx_tab_switch_total_e10s_ms STRING,
      fx_tab_switch_update_ms STRING,
      fx_urlbar_selected_result_index STRING,
      fx_urlbar_selected_result_index_by_type ARRAY<STRUCT<key STRING, value STRING>>,
      fx_urlbar_selected_result_method STRING,
      fx_urlbar_selected_result_type STRING,
      gc_animation_ms STRING,
      gc_max_pause_ms_2 STRING,
      geolocation_request_granted STRING,
      ghost_windows STRING,
      gpu_process_initialization_time_ms STRING,
      gpu_process_launch_time_ms_2 STRING,
      http_channel_disposition STRING,
      http_pageload_is_ssl STRING,
      http_transaction_is_ssl STRING,
      input_event_response_coalesced_ms STRING,
      ipc_read_main_thread_latency_ms ARRAY<STRUCT<key STRING, value STRING>>,
      memory_distribution_among_content ARRAY<STRUCT<key STRING, value STRING>>,
      memory_heap_allocated STRING,
      memory_resident_fast STRING,
      memory_total STRING,
      memory_unique STRING,
      memory_vsize STRING,
      memory_vsize_max_contiguous STRING,
      network_cache_metadata_first_read_time_ms STRING,
      network_cache_v2_hit_time_ms STRING,
      network_cache_v2_miss_time_ms STRING,
      number_of_profiles STRING,
      places_autocomplete_6_first_results_time_ms STRING,
      plugin_shutdown_ms STRING,
      pwmgr_blocklist_num_sites STRING,
      pwmgr_form_autofill_result STRING,
      pwmgr_login_last_used_days STRING,
      pwmgr_login_page_safety STRING,
      pwmgr_manage_copied_password STRING,
      pwmgr_manage_copied_username STRING,
      pwmgr_manage_deleted STRING,
      pwmgr_manage_opened STRING,
      pwmgr_manage_visibility_toggled STRING,
      pwmgr_num_passwords_per_hostname STRING,
      pwmgr_num_saved_passwords STRING,
      pwmgr_prompt_remember_action STRING,
      pwmgr_prompt_update_action STRING,
      pwmgr_saving_enabled STRING,
      sandbox_rejected_syscalls ARRAY<STRUCT<key STRING, value STRING>>,
      search_service_init_ms STRING,
      ssl_handshake_result STRING,
      ssl_handshake_version STRING,
      ssl_tls12_intolerance_reason_pre STRING,
      ssl_tls13_intolerance_reason_pre STRING,
      time_to_first_click_ms STRING,
      time_to_first_interaction_ms STRING,
      time_to_first_key_input_ms STRING,
      time_to_first_mouse_move_ms STRING,
      time_to_first_scroll_ms STRING,
      time_to_non_blank_paint_ms STRING,
      time_to_response_start_ms STRING,
      touch_enabled_device STRING,
      tracking_protection_enabled STRING,
      update_bits_result_complete STRING,
      update_bits_result_partial STRING,
      update_can_use_bits_notify STRING,
      update_download_code_complete STRING,
      update_download_code_partial STRING,
      update_state_code_complete_stage STRING,
      update_state_code_complete_startup STRING,
      update_state_code_partial_stage STRING,
      update_state_code_partial_startup STRING,
      update_status_error_code_complete_stage STRING,
      update_status_error_code_complete_startup STRING,
      update_status_error_code_partial_stage STRING,
      update_status_error_code_partial_startup STRING,
      webext_background_page_load_ms STRING,
      webext_browseraction_popup_open_ms STRING,
      webext_browseraction_popup_preload_result_count STRING,
      webext_content_script_injection_ms STRING,
      webext_extension_startup_ms STRING,
      webext_pageaction_popup_open_ms STRING,
      webext_storage_local_get_ms STRING,
      webext_storage_local_set_ms STRING,
      webvr_time_spent_viewing_in_2d STRING,
      webvr_time_spent_viewing_in_oculus STRING,
      webvr_time_spent_viewing_in_openvr STRING,
      webvr_users_view_in STRING
    >
  >
)
RETURNS STRUCT<
    histogram_parent_a11y_consumers ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_a11y_instantiated_flag BOOLEAN,
    histogram_parent_cert_validation_success_by_ca ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_cert_validation_success_by_ca ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_checkerboard_severity ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_checkerboard_severity ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_checkerboard_severity ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_composite_time ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_composite_time ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_composite_time ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_parent_content_frame_time ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_content_frame_time ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_content_paint_time ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_content_paint_time ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_cookie_behavior ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_cycle_collector_max_pause ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_cycle_collector_max_pause ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_aboutdebugging_opened_count INT64,
    histogram_content_devtools_aboutdebugging_opened_count INT64,
    histogram_parent_devtools_about_devtools_opened_key ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_devtools_about_devtools_opened_reason ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_devtools_accessibility_picker_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_devtools_accessibility_picker_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_accessibility_service_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_devtools_accessibility_service_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_accessibility_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_devtools_accessibility_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_animationinspector_opened_count INT64,
    histogram_content_devtools_animationinspector_opened_count INT64,
    histogram_parent_devtools_browserconsole_opened_count INT64,
    histogram_content_devtools_browserconsole_opened_count INT64,
    histogram_parent_devtools_canvasdebugger_opened_count INT64,
    histogram_content_devtools_canvasdebugger_opened_count INT64,
    histogram_parent_devtools_computedview_opened_count INT64,
    histogram_content_devtools_computedview_opened_count INT64,
    histogram_parent_devtools_custom_opened_count INT64,
    histogram_content_devtools_custom_opened_count INT64,
    histogram_parent_devtools_dom_opened_count INT64,
    histogram_content_devtools_dom_opened_count INT64,
    histogram_parent_devtools_entry_point ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_devtools_eyedropper_opened_count INT64,
    histogram_content_devtools_eyedropper_opened_count INT64,
    histogram_parent_devtools_fonteditor_font_type_displayed ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_devtools_fonteditor_n_fonts_rendered ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_content_devtools_fonteditor_n_fonts_rendered ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_fonteditor_n_font_axes ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_content_devtools_fonteditor_n_font_axes ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_fontinspector_opened_count INT64,
    histogram_content_devtools_fontinspector_opened_count INT64,
    histogram_parent_devtools_inspector_opened_count INT64,
    histogram_content_devtools_inspector_opened_count INT64,
    histogram_parent_devtools_jsbrowserdebugger_opened_count INT64,
    histogram_content_devtools_jsbrowserdebugger_opened_count INT64,
    histogram_parent_devtools_jsdebugger_opened_count INT64,
    histogram_content_devtools_jsdebugger_opened_count INT64,
    histogram_parent_devtools_jsprofiler_opened_count INT64,
    histogram_content_devtools_jsprofiler_opened_count INT64,
    histogram_parent_devtools_layoutview_opened_count INT64,
    histogram_content_devtools_layoutview_opened_count INT64,
    histogram_parent_devtools_memory_opened_count INT64,
    histogram_content_devtools_memory_opened_count INT64,
    histogram_parent_devtools_menu_eyedropper_opened_count INT64,
    histogram_content_devtools_menu_eyedropper_opened_count INT64,
    histogram_parent_devtools_netmonitor_opened_count INT64,
    histogram_content_devtools_netmonitor_opened_count INT64,
    histogram_parent_devtools_options_opened_count INT64,
    histogram_content_devtools_options_opened_count INT64,
    histogram_parent_devtools_paintflashing_opened_count INT64,
    histogram_content_devtools_paintflashing_opened_count INT64,
    histogram_parent_devtools_picker_eyedropper_opened_count INT64,
    histogram_content_devtools_picker_eyedropper_opened_count INT64,
    histogram_parent_devtools_responsive_opened_count INT64,
    histogram_content_devtools_responsive_opened_count INT64,
    histogram_parent_devtools_ruleview_opened_count INT64,
    histogram_content_devtools_ruleview_opened_count INT64,
    histogram_parent_devtools_scratchpad_opened_count INT64,
    histogram_content_devtools_scratchpad_opened_count INT64,
    histogram_parent_devtools_scratchpad_window_opened_count INT64,
    histogram_content_devtools_scratchpad_window_opened_count INT64,
    histogram_parent_devtools_shadereditor_opened_count INT64,
    histogram_content_devtools_shadereditor_opened_count INT64,
    histogram_parent_devtools_storage_opened_count INT64,
    histogram_content_devtools_storage_opened_count INT64,
    histogram_parent_devtools_styleeditor_opened_count INT64,
    histogram_content_devtools_styleeditor_opened_count INT64,
    histogram_parent_devtools_toolbox_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_devtools_toolbox_time_active_seconds ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_devtools_webaudioeditor_opened_count INT64,
    histogram_content_devtools_webaudioeditor_opened_count INT64,
    histogram_parent_devtools_webconsole_opened_count INT64,
    histogram_content_devtools_webconsole_opened_count INT64,
    histogram_parent_devtools_webide_opened_count INT64,
    histogram_content_devtools_webide_opened_count INT64,
    histogram_parent_dns_failed_lookup_time ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_dns_lookup_time ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_new_window_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_page_load_ms_2 ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_fx_page_load_ms_2 ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_searchbar_selected_result_method ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_content_fx_searchbar_selected_result_method ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_fx_session_restore_restore_window_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_session_restore_startup_init_session_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_session_restore_startup_onload_initial_window_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_tab_close_time_anim_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_tab_switch_total_e10s_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_tab_switch_update_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_urlbar_selected_result_index ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_fx_urlbar_selected_result_index ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_fx_urlbar_selected_result_index_by_type ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key INT64, value INT64>>>>,
    histogram_content_fx_urlbar_selected_result_index_by_type ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key INT64, value INT64>>>>,
    histogram_parent_fx_urlbar_selected_result_method ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_content_fx_urlbar_selected_result_method ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_fx_urlbar_selected_result_type ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_fx_urlbar_selected_result_type ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_gc_animation_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_gc_animation_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_gc_max_pause_ms_2 ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_gc_max_pause_ms_2 ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_geolocation_request_granted ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_geolocation_request_granted ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_ghost_windows ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_ghost_windows ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_gpu_process_initialization_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_gpu_process_initialization_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_gpu_process_initialization_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_gpu_process_launch_time_ms_2 ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_gpu_process_launch_time_ms_2 ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_http_channel_disposition ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_http_channel_disposition ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_http_pageload_is_ssl ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_http_pageload_is_ssl ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_http_transaction_is_ssl ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_http_transaction_is_ssl ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_input_event_response_coalesced_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_input_event_response_coalesced_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_ipc_read_main_thread_latency_ms ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key INT64, value INT64>>>>,
    histogram_content_ipc_read_main_thread_latency_ms ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key INT64, value INT64>>>>,
    histogram_gpu_ipc_read_main_thread_latency_ms ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key INT64, value INT64>>>>,
    histogram_parent_memory_distribution_among_content ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key INT64, value INT64>>>>,
    histogram_parent_memory_heap_allocated ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_memory_heap_allocated ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_memory_resident_fast ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_memory_resident_fast ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_memory_total ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_memory_unique ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_memory_unique ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_memory_unique_content_startup ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_memory_vsize ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_memory_vsize ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_memory_vsize_max_contiguous ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_memory_vsize_max_contiguous ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_network_cache_metadata_first_read_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_network_cache_metadata_first_read_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_network_cache_v2_hit_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_network_cache_v2_hit_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_network_cache_v2_miss_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_network_cache_v2_miss_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_number_of_profiles INT64,
    histogram_content_number_of_profiles INT64,
    histogram_parent_places_autocomplete_6_first_results_time_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_plugin_shutdown_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_plugin_shutdown_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_blocklist_num_sites ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_form_autofill_result ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_pwmgr_form_autofill_result ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_login_last_used_days ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_login_page_safety ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_pwmgr_login_page_safety ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_manage_copied_password INT64,
    histogram_content_pwmgr_manage_copied_password INT64,
    histogram_parent_pwmgr_manage_copied_username INT64,
    histogram_content_pwmgr_manage_copied_username INT64,
    histogram_parent_pwmgr_manage_deleted INT64,
    histogram_content_pwmgr_manage_deleted INT64,
    histogram_parent_pwmgr_manage_opened ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_pwmgr_manage_opened ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_manage_visibility_toggled ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_num_passwords_per_hostname ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_num_saved_passwords ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_prompt_remember_action ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_prompt_update_action ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_pwmgr_saving_enabled ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_sandbox_rejected_syscalls ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_content_sandbox_rejected_syscalls ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_search_service_init_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_ssl_handshake_result ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_ssl_handshake_result ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_ssl_handshake_version ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_ssl_handshake_version ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_ssl_tls12_intolerance_reason_pre ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_ssl_tls12_intolerance_reason_pre ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_ssl_tls13_intolerance_reason_pre ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_ssl_tls13_intolerance_reason_pre ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_dom_complete_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_dom_content_loaded_end_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_dom_content_loaded_start_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_dom_interactive_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_dom_loading_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_first_click_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_first_click_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_first_interaction_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_first_interaction_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_first_key_input_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_first_key_input_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_first_mouse_move_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_first_mouse_move_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_first_scroll_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_first_scroll_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_load_event_end_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_load_event_start_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_non_blank_paint_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_non_blank_paint_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_time_to_response_start_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_time_to_response_start_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_touch_enabled_device ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_tracking_protection_enabled ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_can_use_bits_notify ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_update_download_code_partial ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_download_code_complete ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_bits_result_partial ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_bits_result_complete ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_state_code_partial_stage ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_state_code_complete_stage ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_status_error_code_complete_stage ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_status_error_code_partial_stage ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_state_code_partial_startup ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_state_code_complete_startup ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_status_error_code_partial_startup ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_update_status_error_code_complete_startup ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_all_uptake_remote_content_result_1 ARRAY<STRUCT<key STRING, value ARRAY<STRUCT<key STRING, value INT64>>>,
    histogram_parent_webext_background_page_load_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webext_browseraction_popup_open_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webext_browseraction_popup_preload_result_count ARRAY<STRUCT<key STRING, value INT64>>,
    histogram_parent_webext_content_script_injection_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_webext_content_script_injection_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webext_extension_startup_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webext_pageaction_popup_open_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webext_storage_local_get_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_webext_storage_local_get_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webext_storage_local_set_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_webext_storage_local_set_ms ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webvr_time_spent_viewing_in_2d ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_webvr_time_spent_viewing_in_2d ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webvr_time_spent_viewing_in_oculus ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_webvr_time_spent_viewing_in_oculus ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webvr_time_spent_viewing_in_openvr ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_webvr_time_spent_viewing_in_openvr ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_parent_webvr_users_view_in ARRAY<STRUCT<key INT64, value INT64>>,
--  histogram_gpu_webvr_users_view_in ARRAY<STRUCT<key INT64, value INT64>>,
    histogram_content_webvr_users_view_in ARRAY<STRUCT<key INT64, value INT64>>
>
LANGUAGE js AS """
function extractHistogramMap(histogram) {
  return JSON.parse(histogram).values;
}
function extractCountHistogram(histogram) {
  return extractHistogramMap(histogram)["0"];
}
function extractFlagHistogram(histogram) {
  let values = extractHistogramMap(histogram);
  if (values["0"] === 0 && values["1"] === 1) {
    return true;
  } else if (values["0"] === 1 && values["1"] === 0) {
    return false;
  }
}
function extractCategoricalHistogramMap(histogram, labels) {
  let result = [];
  for (let [key, value] of Object.entries(extractHistogramMap(histogram))) {
    try {
      result.push({key: labels[parseInt(key)], value})
    } catch (error) {}
  }
  return result;
}
return {
  histogram_parent_a11y_consumers: extractHistogramMap(histograms.parent.a11y_consumers),
  histogram_parent_a11y_instantiated_flag: extractFlagHistogram(histograms.parent.a11y_instantiated_flag),
  histogram_parent_cert_validation_success_by_ca: extractHistogramMap(histograms.parent.cert_validation_success_by_ca),
  histogram_content_cert_validation_success_by_ca: extractHistogramMap(histograms.content.cert_validation_success_by_ca),
  histogram_parent_checkerboard_severity: extractHistogramMap(histograms.parent.checkerboard_severity),
  histogram_content_checkerboard_severity: extractHistogramMap(histograms.content.checkerboard_severity),
//histogram_gpu_checkerboard_severity: extractHistogramMap(histograms.gpu.checkerboard_severity),
  histogram_parent_composite_time: extractHistogramMap(histograms.parent.composite_time),
  histogram_content_composite_time: extractHistogramMap(histograms.content.composite_time),
//histogram_gpu_composite_time: extractHistogramMap(histograms.gpu.composite_time),
//histogram_parent_content_frame_time: extractHistogramMap(histograms.parent.content_frame_time),
//histogram_gpu_content_frame_time: extractHistogramMap(histograms.gpu.content_frame_time),
  histogram_parent_content_paint_time: extractHistogramMap(histograms.parent.content_paint_time),
  histogram_content_content_paint_time: extractHistogramMap(histograms.content.content_paint_time),
  histogram_parent_cookie_behavior: extractHistogramMap(histograms.parent.cookie_behavior),
  histogram_parent_cycle_collector_max_pause: extractHistogramMap(histograms.parent.cycle_collector_max_pause),
  histogram_content_cycle_collector_max_pause: extractHistogramMap(histograms.content.cycle_collector_max_pause),
  histogram_parent_devtools_aboutdebugging_opened_count: extractCountHistogram(histograms.parent.devtools_aboutdebugging_opened_count),
  histogram_content_devtools_aboutdebugging_opened_count: extractCountHistogram(histograms.content.devtools_aboutdebugging_opened_count),
  histogram_parent_devtools_about_devtools_opened_key: extractCategoricalHistogramMap(histograms.parent.devtools_about_devtools_opened_key, []),
  histogram_parent_devtools_about_devtools_opened_reason: extractCategoricalHistogramMap(histograms.parent.devtools_about_devtools_opened_reason, []),
  histogram_parent_devtools_accessibility_picker_time_active_seconds: extractHistogramMap(histograms.parent.devtools_accessibility_picker_time_active_seconds),
  histogram_content_devtools_accessibility_picker_time_active_seconds: extractHistogramMap(histograms.content.devtools_accessibility_picker_time_active_seconds),
  histogram_parent_devtools_accessibility_service_time_active_seconds: extractHistogramMap(histograms.parent.devtools_accessibility_service_time_active_seconds),
  histogram_content_devtools_accessibility_service_time_active_seconds: extractHistogramMap(histograms.content.devtools_accessibility_service_time_active_seconds),
  histogram_parent_devtools_accessibility_time_active_seconds: extractHistogramMap(histograms.parent.devtools_accessibility_time_active_seconds),
  histogram_content_devtools_accessibility_time_active_seconds: extractHistogramMap(histograms.content.devtools_accessibility_time_active_seconds),
  histogram_parent_devtools_animationinspector_opened_count: extractCountHistogram(histograms.parent.devtools_animationinspector_opened_count),
  histogram_content_devtools_animationinspector_opened_count: extractCountHistogram(histograms.content.devtools_animationinspector_opened_count),
  histogram_parent_devtools_browserconsole_opened_count: extractCountHistogram(histograms.parent.devtools_browserconsole_opened_count),
  histogram_content_devtools_browserconsole_opened_count: extractCountHistogram(histograms.content.devtools_browserconsole_opened_count),
  histogram_parent_devtools_canvasdebugger_opened_count: extractCountHistogram(histograms.parent.devtools_canvasdebugger_opened_count),
  histogram_content_devtools_canvasdebugger_opened_count: extractCountHistogram(histograms.content.devtools_canvasdebugger_opened_count),
  histogram_parent_devtools_computedview_opened_count: extractCountHistogram(histograms.parent.devtools_computedview_opened_count),
  histogram_content_devtools_computedview_opened_count: extractCountHistogram(histograms.content.devtools_computedview_opened_count),
  histogram_parent_devtools_custom_opened_count: extractCountHistogram(histograms.parent.devtools_custom_opened_count),
  histogram_content_devtools_custom_opened_count: extractCountHistogram(histograms.content.devtools_custom_opened_count),
  histogram_parent_devtools_dom_opened_count: extractCountHistogram(histograms.parent.devtools_dom_opened_count),
  histogram_content_devtools_dom_opened_count: extractCountHistogram(histograms.content.devtools_dom_opened_count),
  histogram_parent_devtools_entry_point: extractCategoricalHistogramMap(
    histograms.parent.devtools_entry_point,
    ['KeyShortcut', 'SystemMenu', 'HamburgerMenu', 'ContextMenu', 'CommandLine', 'SessionRestore']
  ),
  histogram_parent_devtools_eyedropper_opened_count: extractCountHistogram(histograms.parent.devtools_eyedropper_opened_count),
  histogram_content_devtools_eyedropper_opened_count: extractCountHistogram(histograms.content.devtools_eyedropper_opened_count),
  histogram_parent_devtools_fonteditor_font_type_displayed: extractCategoricalHistogramMap(
    histograms.parent.devtools_fonteditor_font_type_displayed,
    ['variable', 'nonvariable']
  ),
  histogram_parent_devtools_fonteditor_n_fonts_rendered: extractHistogramMap(histograms.parent.devtools_fonteditor_n_fonts_rendered),
//histogram_content_devtools_fonteditor_n_fonts_rendered: extractHistogramMap(histograms.content.devtools_fonteditor_n_fonts_rendered),
  histogram_parent_devtools_fonteditor_n_font_axes: extractHistogramMap(histograms.parent.devtools_fonteditor_n_font_axes),
//histogram_content_devtools_fonteditor_n_font_axes: extractHistogramMap(histograms.content.devtools_fonteditor_n_font_axes),
  histogram_parent_devtools_fontinspector_opened_count: extractCountHistogram(histograms.parent.devtools_fontinspector_opened_count),
  histogram_content_devtools_fontinspector_opened_count: extractCountHistogram(histograms.content.devtools_fontinspector_opened_count),
  histogram_parent_devtools_inspector_opened_count: extractCountHistogram(histograms.parent.devtools_inspector_opened_count),
  histogram_content_devtools_inspector_opened_count: extractCountHistogram(histograms.content.devtools_inspector_opened_count),
  histogram_parent_devtools_jsbrowserdebugger_opened_count: extractCountHistogram(histograms.parent.devtools_jsbrowserdebugger_opened_count),
  histogram_content_devtools_jsbrowserdebugger_opened_count: extractCountHistogram(histograms.content.devtools_jsbrowserdebugger_opened_count),
  histogram_parent_devtools_jsdebugger_opened_count: extractCountHistogram(histograms.parent.devtools_jsdebugger_opened_count),
  histogram_content_devtools_jsdebugger_opened_count: extractCountHistogram(histograms.content.devtools_jsdebugger_opened_count),
  histogram_parent_devtools_jsprofiler_opened_count: extractCountHistogram(histograms.parent.devtools_jsprofiler_opened_count),
  histogram_content_devtools_jsprofiler_opened_count: extractCountHistogram(histograms.content.devtools_jsprofiler_opened_count),
  histogram_parent_devtools_layoutview_opened_count: extractCountHistogram(histograms.parent.devtools_layoutview_opened_count),
  histogram_content_devtools_layoutview_opened_count: extractCountHistogram(histograms.content.devtools_layoutview_opened_count),
  histogram_parent_devtools_memory_opened_count: extractCountHistogram(histograms.parent.devtools_memory_opened_count),
  histogram_content_devtools_memory_opened_count: extractCountHistogram(histograms.content.devtools_memory_opened_count),
  histogram_parent_devtools_menu_eyedropper_opened_count: extractCountHistogram(histograms.parent.devtools_menu_eyedropper_opened_count),
  histogram_content_devtools_menu_eyedropper_opened_count: extractCountHistogram(histograms.content.devtools_menu_eyedropper_opened_count),
  histogram_parent_devtools_netmonitor_opened_count: extractCountHistogram(histograms.parent.devtools_netmonitor_opened_count),
  histogram_content_devtools_netmonitor_opened_count: extractCountHistogram(histograms.content.devtools_netmonitor_opened_count),
  histogram_parent_devtools_options_opened_count: extractCountHistogram(histograms.parent.devtools_options_opened_count),
  histogram_content_devtools_options_opened_count: extractCountHistogram(histograms.content.devtools_options_opened_count),
  histogram_parent_devtools_paintflashing_opened_count: extractCountHistogram(histograms.parent.devtools_paintflashing_opened_count),
  histogram_content_devtools_paintflashing_opened_count: extractCountHistogram(histograms.content.devtools_paintflashing_opened_count),
  histogram_parent_devtools_picker_eyedropper_opened_count: extractCountHistogram(histograms.parent.devtools_picker_eyedropper_opened_count),
  histogram_content_devtools_picker_eyedropper_opened_count: extractCountHistogram(histograms.content.devtools_picker_eyedropper_opened_count),
  histogram_parent_devtools_responsive_opened_count: extractCountHistogram(histograms.parent.devtools_responsive_opened_count),
  histogram_content_devtools_responsive_opened_count: extractCountHistogram(histograms.content.devtools_responsive_opened_count),
  histogram_parent_devtools_ruleview_opened_count: extractCountHistogram(histograms.parent.devtools_ruleview_opened_count),
  histogram_content_devtools_ruleview_opened_count: extractCountHistogram(histograms.content.devtools_ruleview_opened_count),
  histogram_parent_devtools_scratchpad_opened_count: extractCountHistogram(histograms.parent.devtools_scratchpad_opened_count),
  histogram_content_devtools_scratchpad_opened_count: extractCountHistogram(histograms.content.devtools_scratchpad_opened_count),
  histogram_parent_devtools_scratchpad_window_opened_count: extractCountHistogram(histograms.parent.devtools_scratchpad_window_opened_count),
  histogram_content_devtools_scratchpad_window_opened_count: extractCountHistogram(histograms.content.devtools_scratchpad_window_opened_count),
  histogram_parent_devtools_shadereditor_opened_count: extractCountHistogram(histograms.parent.devtools_shadereditor_opened_count),
  histogram_content_devtools_shadereditor_opened_count: extractCountHistogram(histograms.content.devtools_shadereditor_opened_count),
  histogram_parent_devtools_storage_opened_count: extractCountHistogram(histograms.parent.devtools_storage_opened_count),
  histogram_content_devtools_storage_opened_count: extractCountHistogram(histograms.content.devtools_storage_opened_count),
  histogram_parent_devtools_styleeditor_opened_count: extractCountHistogram(histograms.parent.devtools_styleeditor_opened_count),
  histogram_content_devtools_styleeditor_opened_count: extractCountHistogram(histograms.content.devtools_styleeditor_opened_count),
  histogram_parent_devtools_toolbox_time_active_seconds: extractHistogramMap(histograms.parent.devtools_toolbox_time_active_seconds),
  histogram_content_devtools_toolbox_time_active_seconds: extractHistogramMap(histograms.content.devtools_toolbox_time_active_seconds),
  histogram_parent_devtools_webaudioeditor_opened_count: extractCountHistogram(histograms.parent.devtools_webaudioeditor_opened_count),
  histogram_content_devtools_webaudioeditor_opened_count: extractCountHistogram(histograms.content.devtools_webaudioeditor_opened_count),
  histogram_parent_devtools_webconsole_opened_count: extractCountHistogram(histograms.parent.devtools_webconsole_opened_count),
  histogram_content_devtools_webconsole_opened_count: extractCountHistogram(histograms.content.devtools_webconsole_opened_count),
  histogram_parent_devtools_webide_opened_count: extractCountHistogram(histograms.parent.devtools_webide_opened_count),
  histogram_content_devtools_webide_opened_count: extractCountHistogram(histograms.content.devtools_webide_opened_count),
  histogram_parent_dns_failed_lookup_time: extractHistogramMap(histograms.parent.dns_failed_lookup_time),
  histogram_parent_dns_lookup_time: extractHistogramMap(histograms.parent.dns_lookup_time),
  histogram_parent_fx_new_window_ms: extractHistogramMap(histograms.parent.fx_new_window_ms),
  histogram_parent_fx_page_load_ms_2: extractHistogramMap(histograms.parent.fx_page_load_ms_2),
  histogram_content_fx_page_load_ms_2: extractHistogramMap(histograms.content.fx_page_load_ms_2),
  histogram_parent_fx_searchbar_selected_result_method: extractCategoricalHistogramMap(
    histograms.parent.fx_searchbar_selected_result_method,
    ['enter', 'enterSelection', 'click']
  ),
  histogram_content_fx_searchbar_selected_result_method: extractCategoricalHistogramMap(
    histograms.content.fx_searchbar_selected_result_method,
    ['enter', 'enterSelection', 'click']
  ),
  histogram_parent_fx_session_restore_restore_window_ms: extractHistogramMap(histograms.parent.fx_session_restore_restore_window_ms),
  histogram_parent_fx_session_restore_startup_init_session_ms: extractHistogramMap(histograms.parent.fx_session_restore_startup_init_session_ms),
  histogram_parent_fx_session_restore_startup_onload_initial_window_ms: extractHistogramMap(histograms.parent.fx_session_restore_startup_onload_initial_window_ms),
  histogram_parent_fx_tab_close_time_anim_ms: extractHistogramMap(histograms.parent.fx_tab_close_time_anim_ms),
  histogram_parent_fx_tab_switch_total_e10s_ms: extractHistogramMap(histograms.parent.fx_tab_switch_total_e10s_ms),
  histogram_parent_fx_tab_switch_update_ms: extractHistogramMap(histograms.parent.fx_tab_switch_update_ms),
  histogram_parent_fx_urlbar_selected_result_index: extractHistogramMap(histograms.parent.fx_urlbar_selected_result_index),
  histogram_content_fx_urlbar_selected_result_index: extractHistogramMap(histograms.content.fx_urlbar_selected_result_index),
  histogram_parent_fx_urlbar_selected_result_index_by_type: histograms.parent.fx_urlbar_selected_result_index_by_type.map(element -> {
    return {key: element.key, value: extractHistogramMap(value)};
  }),
  histogram_content_fx_urlbar_selected_result_index_by_type: histograms.content.fx_urlbar_selected_result_index_by_type.map(element -> {
    return {key: element.key, value: extractHistogramMap(value)};
  }),
  histogram_parent_fx_urlbar_selected_result_method: extractCategoricalHistogramMap(
    histograms.parent.fx_urlbar_selected_result_method,
    ['enter', 'enterSelection', 'click', 'arrowEnterSelection', 'tabEnterSelection', 'rightClickEnter']
  ),
  histogram_content_fx_urlbar_selected_result_method: extractCategoricalHistogramMap(
    histograms.content.fx_urlbar_selected_result_method,
    ['enter', 'enterSelection', 'click', 'arrowEnterSelection', 'tabEnterSelection', 'rightClickEnter']
  ),
  histogram_parent_fx_urlbar_selected_result_type: extractHistogramMap(histograms.parent.fx_urlbar_selected_result_type),
  histogram_content_fx_urlbar_selected_result_type: extractHistogramMap(histograms.content.fx_urlbar_selected_result_type),
  histogram_parent_gc_animation_ms: extractHistogramMap(histograms.parent.gc_animation_ms),
  histogram_content_gc_animation_ms: extractHistogramMap(histograms.content.gc_animation_ms),
  histogram_parent_gc_max_pause_ms_2: extractHistogramMap(histograms.parent.gc_max_pause_ms_2),
  histogram_content_gc_max_pause_ms_2: extractHistogramMap(histograms.content.gc_max_pause_ms_2),
  histogram_parent_geolocation_request_granted: extractHistogramMap(histograms.parent.geolocation_request_granted),
  histogram_content_geolocation_request_granted: extractHistogramMap(histograms.content.geolocation_request_granted),
  histogram_parent_ghost_windows: extractHistogramMap(histograms.parent.ghost_windows),
  histogram_content_ghost_windows: extractHistogramMap(histograms.content.ghost_windows),
  histogram_parent_gpu_process_initialization_time_ms: extractHistogramMap(histograms.parent.gpu_process_initialization_time_ms),
  histogram_content_gpu_process_initialization_time_ms: extractHistogramMap(histograms.content.gpu_process_initialization_time_ms),
//histogram_gpu_gpu_process_initialization_time_ms: extractHistogramMap(histograms.gpu.gpu_process_initialization_time_ms),
  histogram_parent_gpu_process_launch_time_ms_2: extractHistogramMap(histograms.parent.gpu_process_launch_time_ms_2),
  histogram_content_gpu_process_launch_time_ms_2: extractHistogramMap(histograms.content.gpu_process_launch_time_ms_2),
  histogram_parent_http_channel_disposition: extractHistogramMap(histograms.parent.http_channel_disposition),
  histogram_content_http_channel_disposition: extractHistogramMap(histograms.content.http_channel_disposition),
  histogram_parent_http_pageload_is_ssl: extractHistogramMap(histograms.parent.http_pageload_is_ssl),
  histogram_content_http_pageload_is_ssl: extractHistogramMap(histograms.content.http_pageload_is_ssl),
  histogram_parent_http_transaction_is_ssl: extractHistogramMap(histograms.parent.http_transaction_is_ssl),
  histogram_content_http_transaction_is_ssl: extractHistogramMap(histograms.content.http_transaction_is_ssl),
  histogram_parent_input_event_response_coalesced_ms: extractHistogramMap(histograms.parent.input_event_response_coalesced_ms),
  histogram_content_input_event_response_coalesced_ms: extractHistogramMap(histograms.content.input_event_response_coalesced_ms),
  histogram_parent_ipc_read_main_thread_latency_ms: histograms.parent.ipc_read_main_thread_latency_ms.map(element -> {
    return {key: element.key, value: extractHistogramMap(value)};
  }),
  histogram_content_ipc_read_main_thread_latency_ms: histograms.content.ipc_read_main_thread_latency_ms.map(element -> {
    return {key: element.key, value: extractHistogramMap(value)};
  }),
  histogram_gpu_ipc_read_main_thread_latency_ms: histograms.gpu.ipc_read_main_thread_latency_ms.map(element -> {
    return {key: element.key, value: extractHistogramMap(value)};
  }),
  histogram_parent_memory_distribution_among_content: histograms.parent.memory_distribution_among_content.map(element -> {
    return {key: element.key, value: extractHistogramMap(value)};
  }),
  histogram_parent_memory_heap_allocated: extractHistogramMap(histograms.parent.memory_heap_allocated),
  histogram_content_memory_heap_allocated: extractHistogramMap(histograms.content.memory_heap_allocated),
  histogram_parent_memory_resident_fast: extractHistogramMap(histograms.parent.memory_resident_fast),
  histogram_content_memory_resident_fast: extractHistogramMap(histograms.content.memory_resident_fast),
  histogram_parent_memory_total: extractHistogramMap(histograms.parent.memory_total),
  histogram_parent_memory_unique: extractHistogramMap(histograms.parent.memory_unique),
  histogram_content_memory_unique: extractHistogramMap(histograms.content.memory_unique),
  histogram_content_memory_unique_content_startup: extractHistogramMap(histograms.content.memory_unique_content_startup),
  histogram_parent_memory_vsize: extractHistogramMap(histograms.parent.memory_vsize),
  histogram_content_memory_vsize: extractHistogramMap(histograms.content.memory_vsize),
  histogram_parent_memory_vsize_max_contiguous: extractHistogramMap(histograms.parent.memory_vsize_max_contiguous),
  histogram_content_memory_vsize_max_contiguous: extractHistogramMap(histograms.content.memory_vsize_max_contiguous),
  histogram_parent_network_cache_metadata_first_read_time_ms: extractHistogramMap(histograms.parent.network_cache_metadata_first_read_time_ms),
  histogram_content_network_cache_metadata_first_read_time_ms: extractHistogramMap(histograms.content.network_cache_metadata_first_read_time_ms),
  histogram_parent_network_cache_v2_hit_time_ms: extractHistogramMap(histograms.parent.network_cache_v2_hit_time_ms),
  histogram_content_network_cache_v2_hit_time_ms: extractHistogramMap(histograms.content.network_cache_v2_hit_time_ms),
  histogram_parent_network_cache_v2_miss_time_ms: extractHistogramMap(histograms.parent.network_cache_v2_miss_time_ms),
  histogram_content_network_cache_v2_miss_time_ms: extractHistogramMap(histograms.content.network_cache_v2_miss_time_ms),
  histogram_parent_number_of_profiles: extractCountHistogram(histograms.parent.number_of_profiles),
  histogram_content_number_of_profiles: extractCountHistogram(histograms.content.number_of_profiles),
  histogram_parent_places_autocomplete_6_first_results_time_ms: extractHistogramMap(histograms.parent.places_autocomplete_6_first_results_time_ms),
  histogram_parent_plugin_shutdown_ms: extractHistogramMap(histograms.parent.plugin_shutdown_ms),
  histogram_content_plugin_shutdown_ms: extractHistogramMap(histograms.content.plugin_shutdown_ms),
  histogram_parent_pwmgr_blocklist_num_sites: extractHistogramMap(histograms.parent.pwmgr_blocklist_num_sites),
  histogram_parent_pwmgr_form_autofill_result: extractHistogramMap(histograms.parent.pwmgr_form_autofill_result),
  histogram_content_pwmgr_form_autofill_result: extractHistogramMap(histograms.content.pwmgr_form_autofill_result),
  histogram_parent_pwmgr_login_last_used_days: extractHistogramMap(histograms.parent.pwmgr_login_last_used_days),
  histogram_parent_pwmgr_login_page_safety: extractHistogramMap(histograms.parent.pwmgr_login_page_safety),
  histogram_content_pwmgr_login_page_safety: extractHistogramMap(histograms.content.pwmgr_login_page_safety),
  histogram_parent_pwmgr_manage_copied_password: extractCountHistogram(histograms.parent.pwmgr_manage_copied_password),
  histogram_content_pwmgr_manage_copied_password: extractCountHistogram(histograms.content.pwmgr_manage_copied_password),
  histogram_parent_pwmgr_manage_copied_username: extractCountHistogram(histograms.parent.pwmgr_manage_copied_username),
  histogram_content_pwmgr_manage_copied_username: extractCountHistogram(histograms.content.pwmgr_manage_copied_username),
  histogram_parent_pwmgr_manage_deleted: extractCountHistogram(histograms.parent.pwmgr_manage_deleted),
  histogram_content_pwmgr_manage_deleted: extractCountHistogram(histograms.content.pwmgr_manage_deleted),
  histogram_parent_pwmgr_manage_opened: extractHistogramMap(histograms.parent.pwmgr_manage_opened),
  histogram_content_pwmgr_manage_opened: extractHistogramMap(histograms.content.pwmgr_manage_opened),
  histogram_parent_pwmgr_manage_visibility_toggled: extractHistogramMap(histograms.parent.pwmgr_manage_visibility_toggled),
  histogram_parent_pwmgr_num_passwords_per_hostname: extractHistogramMap(histograms.parent.pwmgr_num_passwords_per_hostname),
  histogram_parent_pwmgr_num_saved_passwords: extractHistogramMap(histograms.parent.pwmgr_num_saved_passwords),
  histogram_parent_pwmgr_prompt_remember_action: extractHistogramMap(histograms.parent.pwmgr_prompt_remember_action),
  histogram_parent_pwmgr_prompt_update_action: extractHistogramMap(histograms.parent.pwmgr_prompt_update_action),
  histogram_parent_pwmgr_saving_enabled: extractHistogramMap(histograms.parent.pwmgr_saving_enabled),
  histogram_parent_sandbox_rejected_syscalls: histograms.parent.sandbox_rejected_syscalls.map(element -> {
    return {key: element.key, value: extractCountHistogram(value)};
  }),
  histogram_content_sandbox_rejected_syscalls: histograms.content.sandbox_rejected_syscalls.map(element -> {
    return {key: element.key, value: extractCountHistogram(value)};
  }),
  histogram_parent_search_service_init_ms: extractHistogramMap(histograms.parent.search_service_init_ms),
  histogram_parent_ssl_handshake_result: extractHistogramMap(histograms.parent.ssl_handshake_result),
  histogram_content_ssl_handshake_result: extractHistogramMap(histograms.content.ssl_handshake_result),
  histogram_parent_ssl_handshake_version: extractHistogramMap(histograms.parent.ssl_handshake_version),
  histogram_content_ssl_handshake_version: extractHistogramMap(histograms.content.ssl_handshake_version),
  histogram_parent_ssl_tls12_intolerance_reason_pre: extractHistogramMap(histograms.parent.ssl_tls12_intolerance_reason_pre),
  histogram_content_ssl_tls12_intolerance_reason_pre: extractHistogramMap(histograms.content.ssl_tls12_intolerance_reason_pre),
  histogram_parent_ssl_tls13_intolerance_reason_pre: extractHistogramMap(histograms.parent.ssl_tls13_intolerance_reason_pre),
  histogram_content_ssl_tls13_intolerance_reason_pre: extractHistogramMap(histograms.content.ssl_tls13_intolerance_reason_pre),
  histogram_content_time_to_dom_complete_ms: extractHistogramMap(histograms.content.time_to_dom_complete_ms),
  histogram_content_time_to_dom_content_loaded_end_ms: extractHistogramMap(histograms.content.time_to_dom_content_loaded_end_ms),
  histogram_content_time_to_dom_content_loaded_start_ms: extractHistogramMap(histograms.content.time_to_dom_content_loaded_start_ms),
  histogram_content_time_to_dom_interactive_ms: extractHistogramMap(histograms.content.time_to_dom_interactive_ms),
  histogram_content_time_to_dom_loading_ms: extractHistogramMap(histograms.content.time_to_dom_loading_ms),
  histogram_parent_time_to_first_click_ms: extractHistogramMap(histograms.parent.time_to_first_click_ms),
  histogram_content_time_to_first_click_ms: extractHistogramMap(histograms.content.time_to_first_click_ms),
  histogram_parent_time_to_first_interaction_ms: extractHistogramMap(histograms.parent.time_to_first_interaction_ms),
  histogram_content_time_to_first_interaction_ms: extractHistogramMap(histograms.content.time_to_first_interaction_ms),
  histogram_parent_time_to_first_key_input_ms: extractHistogramMap(histograms.parent.time_to_first_key_input_ms),
  histogram_content_time_to_first_key_input_ms: extractHistogramMap(histograms.content.time_to_first_key_input_ms),
  histogram_parent_time_to_first_mouse_move_ms: extractHistogramMap(histograms.parent.time_to_first_mouse_move_ms),
  histogram_content_time_to_first_mouse_move_ms: extractHistogramMap(histograms.content.time_to_first_mouse_move_ms),
  histogram_parent_time_to_first_scroll_ms: extractHistogramMap(histograms.parent.time_to_first_scroll_ms),
  histogram_content_time_to_first_scroll_ms: extractHistogramMap(histograms.content.time_to_first_scroll_ms),
  histogram_content_time_to_load_event_end_ms: extractHistogramMap(histograms.content.time_to_load_event_end_ms),
  histogram_content_time_to_load_event_start_ms: extractHistogramMap(histograms.content.time_to_load_event_start_ms),
  histogram_parent_time_to_non_blank_paint_ms: extractHistogramMap(histograms.parent.time_to_non_blank_paint_ms),
  histogram_content_time_to_non_blank_paint_ms: extractHistogramMap(histograms.content.time_to_non_blank_paint_ms),
  histogram_parent_time_to_response_start_ms: extractHistogramMap(histograms.parent.time_to_response_start_ms),
  histogram_content_time_to_response_start_ms: extractHistogramMap(histograms.content.time_to_response_start_ms),
  histogram_parent_touch_enabled_device: extractHistogramMap(histograms.parent.touch_enabled_device),
  histogram_parent_tracking_protection_enabled: extractHistogramMap(histograms.parent.tracking_protection_enabled),
  histogram_parent_update_can_use_bits_notify: extractCategoricalHistogramMap(
    histograms.parent.update_can_use_bits_notify,
    ['CanUseBits', 'NoBits_NotWindows', 'NoBits_FeatureOff', 'NoBits_Pref', 'NoBits_Proxy', 'NoBits_OtherUser']
  ),
  histogram_parent_update_download_code_partial: extractHistogramMap(histograms.parent.update_download_code_partial),
  histogram_parent_update_download_code_complete: extractHistogramMap(histograms.parent.update_download_code_complete),
  histogram_parent_update_bits_result_partial: extractHistogramMap(histograms.parent.update_bits_result_partial),
  histogram_parent_update_bits_result_complete: extractHistogramMap(histograms.parent.update_bits_result_complete),
  histogram_parent_update_state_code_partial_stage: extractHistogramMap(histograms.parent.update_state_code_partial_stage),
  histogram_parent_update_state_code_complete_stage: extractHistogramMap(histograms.parent.update_state_code_complete_stage),
  histogram_parent_update_status_error_code_complete_stage: extractHistogramMap(histograms.parent.update_status_error_code_complete_stage),
  histogram_parent_update_status_error_code_partial_stage: extractHistogramMap(histograms.parent.update_status_error_code_partial_stage),
  histogram_parent_update_state_code_partial_startup: extractHistogramMap(histograms.parent.update_state_code_partial_startup),
  histogram_parent_update_state_code_complete_startup: extractHistogramMap(histograms.parent.update_state_code_complete_startup),
  histogram_parent_update_status_error_code_partial_startup: extractHistogramMap(histograms.parent.update_status_error_code_partial_startup),
  histogram_parent_update_status_error_code_complete_startup: extractHistogramMap(histograms.parent.update_status_error_code_complete_startup),
//histogram_all_uptake_remote_content_result_1: histograms.all.uptake_remote_content_result_1.map(element -> {
//  return {
//    key: element.key,
//    value: extractCategoricalHistogramMap(
//      value,
//      [
//        'up_to_date', 'success', 'backoff', 'pref_disabled', 'parse_error', 'content_error', 'sign_error', 'sign_retry_error',
//        'conflict_error', 'sync_error', 'apply_error', 'server_error', 'certificate_error', 'download_error', 'timeout_error',
//        'network_error', 'offline_error', 'cleanup_error', 'unknown_error', 'custom_1_error', 'custom_2_error', 'custom_3_error',
//        'custom_4_error', 'custom_5_error'
//      ]
//    )
//  };
//}),
  histogram_parent_webext_background_page_load_ms: extractHistogramMap(histograms.parent.webext_background_page_load_ms),
  histogram_parent_webext_browseraction_popup_open_ms: extractHistogramMap(histograms.parent.webext_browseraction_popup_open_ms),
  histogram_parent_webext_browseraction_popup_preload_result_count: extractCategoricalHistogramMap(
    histograms.parent.webext_browseraction_popup_preload_result_count,
    ['popupShown', 'clearAfterHover', 'clearAfterMousedown']
  ),
  histogram_parent_webext_content_script_injection_ms: extractHistogramMap(histograms.parent.webext_content_script_injection_ms),
  histogram_content_webext_content_script_injection_ms: extractHistogramMap(histograms.content.webext_content_script_injection_ms),
  histogram_parent_webext_extension_startup_ms: extractHistogramMap(histograms.parent.webext_extension_startup_ms),
  histogram_parent_webext_pageaction_popup_open_ms: extractHistogramMap(histograms.parent.webext_pageaction_popup_open_ms),
  histogram_parent_webext_storage_local_get_ms: extractHistogramMap(histograms.parent.webext_storage_local_get_ms),
  histogram_content_webext_storage_local_get_ms: extractHistogramMap(histograms.content.webext_storage_local_get_ms),
  histogram_parent_webext_storage_local_set_ms: extractHistogramMap(histograms.parent.webext_storage_local_set_ms),
  histogram_content_webext_storage_local_set_ms: extractHistogramMap(histograms.content.webext_storage_local_set_ms),
  histogram_parent_webvr_time_spent_viewing_in_2d: extractHistogramMap(histograms.parent.webvr_time_spent_viewing_in_2d),
  histogram_content_webvr_time_spent_viewing_in_2d: extractHistogramMap(histograms.content.webvr_time_spent_viewing_in_2d),
  histogram_parent_webvr_time_spent_viewing_in_oculus: extractHistogramMap(histograms.parent.webvr_time_spent_viewing_in_oculus),
//histogram_gpu_webvr_time_spent_viewing_in_oculus: extractHistogramMap(histograms.gpu.webvr_time_spent_viewing_in_oculus),
  histogram_parent_webvr_time_spent_viewing_in_openvr: extractHistogramMap(histograms.parent.webvr_time_spent_viewing_in_openvr),
//histogram_gpu_webvr_time_spent_viewing_in_openvr: extractHistogramMap(histograms.gpu.webvr_time_spent_viewing_in_openvr),
  histogram_parent_webvr_users_view_in: extractHistogramMap(histograms.parent.webvr_users_view_in),
//histogram_gpu_webvr_users_view_in: extractHistogramMap(histograms.gpu.webvr_users_view_in),
  histogram_content_webvr_users_view_in: extractHistogramMap(histograms.content.webvr_users_view_in),
}
""";
